Add system assigned managed identity to vm
wls-eng/arm-oraclelinux-wls-admin pull request #78
Opened 2021-02-01 06:46 UTC by zhengchang907

-- Update UI to expose configuration options to users
-- Update mainTemplate.json to accept&pass parameters around
-- Update adminTemplate.json/adminTemplateForCustomSSL.json to add configuration for identity property

2021-02-01 06:48 UTC, zhengchang907 commented
@edburns Hi Ed, could you please review this PR? I've checked that it can be merged with the other [PR(Add Key Vault automation)](https://github.com/wls-eng/arm-oraclelinux-wls-admin/pull/77) without conflicts.

2021-02-02 02:57 UTC, edburns commented on src/main/arm/createUiDefinition.json
> +                    },
I am not sure why you did not use the same configuration I offered in my branch on `arm-oraclelinux-wls`:

```json
                    {
                        "name": "useSystemAssignedManagedIdentity",
                        "label": "Cause a system assigned managed identity to be created for the VM(s).",
                        "type": "Microsoft.Common.CheckBox",
                        "toolTip": "System assigned managed identities enable credential-free secure access to many Azure resources from this VM.",
                        "defaultValue": true
                    },            
...
            "useSystemAssignedManagedIdentity": "[basics('basicsOptional').useSystemAssignedManagedIdentity]",        
```

A checkbox is a better UI element than Yes/No for this use case.

2021-02-02 02:57 UTC, edburns requested changes
See comment on `createUiDefinition`.

2021-02-04 00:05 UTC, edburns commented
Hello @zhengchang907 , I tried to resolve the merge conflicts, but was unable to cleanly do so. Can you please update the PR and resolve the conflicts so it will merge cleanly?

2021-02-04 05:05 UTC, zhengchang907 commented
Hi @edburns , I'll close this PR and re-create one with changes of System Assigned Managed Identity only.

2021-02-04 05:05 UTC, closed without merging